#root api
server:
  servlet:
    context-path: /api

#E-mail user
default:
  sender: demysdcl@gmail.com
  url: http://localhost:8080/api

#E-mail configuration
spring:
  mail:
    host: smtp.gmail.com
    username: yourEmail@gmail.com
    password: yourPassword
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: smtp.gmail.com
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          startttls.enable: true

#Swagger 2
host.full.dns.auth.link: http://localhost:8080/api
app:
  client:
    id: dclfactor
    secret: 123

